name: Ventilairsec Enocean
description: Ventilairsec VMI Purevent integration via Enocean protocol
version: 1.0.0
slug: ventilairsec_enocean
url: https://github.com/fortinric88/Ventilairsec2HA
documentation: https://github.com/fortinric88/Ventilairsec2HA/tree/main/addons/ventilairsec_enocean
source: https://github.com/fortinric88/Ventilairsec2HA
issues: https://github.com/fortinric88/Ventilairsec2HA/issues
homeassistant: "2023.10.0"
codeowners:
  - "@fortinric88"
startup: services
boot: auto
image: ghcr.io/fortinric88/ventilairsec-enocean-{BUILD_ARCH}
arch:
  - amd64
  - armv7
  - arm64

# Hardware and software requirements
requirements:
  - "python >= 3.9"

# USB device access for Enocean dongle
devices:
  - /dev/ttyUSB0
  - /dev/ttyUSB1
  - /dev/ttyACM0
  - /dev/ttyACM1
  - /dev/mem      # For GPIO access
  - /dev/gpiomem  # For GPIO access without root

# Data persistence
volumes:
  logs: /var/log/ventilairsec

# Port mapping
ports:
  55006/tcp: 55006

# Network access
network_mode: host

# System permissions
privileged:
  - NET_ADMIN

# Configuration options
options:
  communication_type: serial
  serial_port: /dev/ttyUSB0
  serial_rate: 115200
  gpio_mode: spi
  gpio_tx_pin: 24
  gpio_rx_pin: 25
  gpio_reset_pin: 17
  socket_port: 55006
  cycle_time: 0.3
  debug_logging: false

# Configuration schema with validation
schema:
  communication_type:
    type: select
    description: Communication method
    options:
      - serial
      - gpio
    default: serial
  serial_port:
    type: select
    description: Serial port for Enocean dongle (if using serial mode)
    options:
      - /dev/ttyUSB0
      - /dev/ttyUSB1
      - /dev/ttyACM0
      - /dev/ttyACM1
      - /dev/ttyAMA0
  serial_rate:
    type: integer
    description: Serial communication speed (baud)
    default: 115200
    validate:
      minimum: 9600
      maximum: 115200
  gpio_mode:
    type: select
    description: GPIO communication mode (if using GPIO)
    options:
      - spi
      - uart
      - i2c
    default: spi
  gpio_tx_pin:
    type: integer
    description: GPIO pin for TX (UART mode) or CS (SPI mode)
    default: 24
    validate:
      minimum: 0
      maximum: 28
  gpio_rx_pin:
    type: integer
    description: GPIO pin for RX (UART mode only)
    default: 25
    validate:
      minimum: 0
      maximum: 28
  gpio_reset_pin:
    type: integer
    description: GPIO pin for RESET (optional, 0 to disable)
    default: 17
    validate:
      minimum: 0
      maximum: 28
  socket_port:
    type: integer
    description: TCP port for internal communication
    default: 55006
    validate:
      minimum: 1000
      maximum: 65535
  cycle_time:
    type: float
    description: Processing cycle time (seconds)
    default: 0.3
    validate:
      minimum: 0.1
      maximum: 1.0
  debug_logging:
    type: boolean
    description: Enable detailed debug logging
    default: false
