name: Ventilairsec Enocean
description: Ventilairsec VMI Purevent integration via Enocean protocol
version: 1.0.0
slug: ventilairsec_enocean
url: https://github.com/fortinric88/Ventilairsec2HA
documentation: https://github.com/fortinric88/Ventilairsec2HA/tree/main/addons/ventilairsec_enocean
source: https://github.com/fortinric88/Ventilairsec2HA
issues: https://github.com/fortinric88/Ventilairsec2HA/issues
homeassistant: "2023.10.0"
codeowners:
  - "@fortinric88"
startup: services
boot: auto
image: ghcr.io/fortinric88/ventilairsec-enocean-{BUILD_ARCH}
arch:
  - amd64
  - armv7
  - arm64

# Hardware and software requirements
requirements:
  - python >= 3.9

# USB device access for Enocean dongle
devices:
  - /dev/ttyUSB0
  - /dev/ttyUSB1
  - /dev/ttyACM0
  - /dev/ttyACM1

# Data persistence
volumes:
  logs: /var/log/ventilairsec

# Network access
network_mode: host

# Configuration options with defaults
options:
  serial_port: /dev/ttyUSB0
  serial_rate: 57600
  mqtt_broker: localhost
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_password: ""
  mqtt_use_tls: false
  debug_logging: false

# Configuration schema with validation
schema:
  serial_port:
    type: select
    description: Serial port for Enocean dongle
    required: true
    options:
      - /dev/ttyUSB0
      - /dev/ttyUSB1
      - /dev/ttyACM0
      - /dev/ttyACM1
      - /dev/ttyAMA0
  serial_rate:
    type: integer
    description: Serial communication speed (baud)
    default: 57600
    required: true
    validate:
      minimum: 9600
      maximum: 115200
  mqtt_broker:
    type: string
    description: MQTT broker hostname or IP address
    default: localhost
    required: true
  mqtt_port:
    type: integer
    description: MQTT broker port (1883 for plain, 8883 for TLS)
    default: 1883
    required: true
    validate:
      minimum: 1
      maximum: 65535
  mqtt_user:
    type: string
    description: MQTT username (leave empty if not required)
    required: false
  mqtt_password:
    type: string
    description: MQTT password (leave empty if not required). Stored securely by Home Assistant.
    required: false
  mqtt_use_tls:
    type: boolean
    description: Use TLS/SSL encryption for MQTT connection (recommended for security)
    default: false
  debug_logging:
    type: boolean
    description: Enable detailed debug logging for troubleshooting
    default: false

